import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kolachi Resturant",
  description: "Generated by create next app, Kolachi Resturant, Web Application, Made By Zain Khan 25, Tailwind, Css",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
